INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Thing", "Apps", 1000000, "2016", "2017");

INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
